### PR TITLE
Added plistutils to plaso preset

### PR DESCRIPTION
**Pull request by Spferical**
For https://github.com/log2timeline/plaso/pull/4790

### CODE REVIEW

**Comment by joachimmetz** [comment]
Looking at https://github.com/strozfriedberg/plistutils this was last updated 7 years ago. Is this being maintained?

**Comment by joachimmetz** [comment]
Looks like alias and bookmarks, alias can likely done easily with dtformats instead. Let me take a look. I'm wary about adding a Python dependency that has not been updated in 7 years given the speed at which Python moves.

**Comment by Spferical** [comment]
> Looking at https://github.com/strozfriedberg/plistutils this was last updated 7 years ago. Is this being maintained?

It was the only existing implementation I found that worked on all my sample data. They responded to a PR I sent last week to fix a python 3.10 api breakage, so I'm not sure it's totally abandoned.

> Looks like alias and bookmarks, alias can likely done easily with dtformats instead. Let me take a look over the weekend. I'm wary about adding a Python dependency that has not been updated in 7 years given the speed at which Python moves.

For sure, thanks!

**Comment by joachimmetz** [comment]
I've created dtfabric based versions of the alias and bookmark data parsers. Would be good to try that on you test data. I'll close this issue since this is no longer needed.

**Pull request closed without merging**
